### ISSUE TITLE
fixed frame and time is incorrect

### ISSUE THREAD

**Issue by ninja777** [dpwivagg/atlas_object_sorting#1]
https://github.com/dpwivagg/atlas_object_sorting/blob/7bf2fe7234ba8c893c4e9e6ab84d1394598d3808/src/atlas_object_sorting_perception.cpp#L73-L74

1. "frame_id" should be the left camera optical frame. Check the tf for the exact name and hardcode it as a constant string. Ideally this should be used from TOUGH_COMMON_NAMES but gazebo plugin has a different namespace, so let's just fix it at node level. 

2. pcl time stamp is in microseconds, not Nano seconds :). I prefer using pcl_conversions package such that the callbacks listen to PCL format and publishers publish as ros format.

**Comment by dpwivagg** [comment]
Thank you @ninja777 for the feedback! Both items are fixed in the commits above.
